[package]
name = "rust_am_lib"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/ku-sldg/rust-am-lib"
[dependencies]
anyhow = "1.0.94"
base64 = "0.22.1"
serde = {version = "1.0.208", features = ["derive"]}
serde_json = "1.0.125"
tokio = { version = "1.44.2", features = ["full"] }
